import { Resend } from 'resend';
import Groq from "groq-sdk";

const resend = new Resend(process.env.RESEND_API_KEY);
const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

export async function POST(req: Request) {
  try {
    const { email, auditData, tool } = await req.json();

    // 1. LLM se Professional Summary Generate Karwana
    const completion = await groq.chat.completions.create({
      messages: [
        {
          role: "system",
          content: "You are a senior FinOps consultant. Write a short, punchy 3-sentence professional audit summary based on the provided data. Use a serious, corporate tone."
        },
        {
          role: "user",
          content: `Tool: ${tool}, Savings: $${auditData.savings}, Reason: ${auditData.reason}`
        }
      ],
      model: "llama-3.3-70b-versatile",
    });

    const aiSummary = completion.choices[0]?.message?.content || auditData.reason;

    // 2. Email bhejna with LLM Summary
    const { data, error } = await resend.emails.send({
      from: 'SpendsAudit AI <onboarding@resend.dev>',
      to: email,
      subject: `Action Required: $${auditData.savings} Savings Identified for ${tool}`,
      html: `
        <div style="font-family: sans-serif; padding: 20px; color: #333;">
          <h2 style="color: #10b981;">Audit Report: ${tool}</h2>
          <p><strong>Executive Summary:</strong><br/>${aiSummary}</p>
          
          <div style="background: #f3f4f6; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <p style="margin: 0;"><strong>Potential Monthly Savings:</strong> $${auditData.savings}</p>
            <p style="margin: 0;"><strong>Annual Recovery:</strong> $${auditData.savings * 12}</p>
          </div>

          <p><strong>Recommended Action:</strong> ${auditData.recommendedAction}</p>
          <hr/>
          <p style="font-size: 12px; color: #666;">This audit was generated by SpendsAudit AI Engine.</p>
        </div>
      `,
    });

    if (error) return Response.json({ error }, { status: 400 });
    return Response.json({ data });
  } catch (error: any) {
    return Response.json({ error: error.message }, { status: 500 });
  }
}